version: '3.8'

services:
  api:
    image: telitsynnikita/swarmlesssonapi:0.2
    ports:
      - 8090:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    logging:
      driver: json-file
      options:
        'max-size': '10m'
        'max-file': '5'